"""
    Data Modelling Storage Service

    API for basic data modelling interaction  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import dmss_api
from dmss_api.api.document_api import DocumentApi  # noqa: E501


class TestDocumentApi(unittest.TestCase):
    """DocumentApi unit test stubs"""

    def setUp(self):
        self.api = DocumentApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_document_add(self):
        """Test case for document_add

        Add By Parent Id  # noqa: E501
        """
        pass

    def test_document_add_simple(self):
        """Test case for document_add_simple

        Add Raw  # noqa: E501
        """
        pass

    def test_document_add_to_path(self):
        """Test case for document_add_to_path

        Add To Path  # noqa: E501
        """
        pass

    def test_document_get_by_id(self):
        """Test case for document_get_by_id

        Get By Id  # noqa: E501
        """
        pass

    def test_document_get_by_path(self):
        """Test case for document_get_by_path

        Get By Path  # noqa: E501
        """
        pass

    def test_document_remove(self):
        """Test case for document_remove

        Remove  # noqa: E501
        """
        pass

    def test_document_remove_by_path(self):
        """Test case for document_remove_by_path

        Remove By Path  # noqa: E501
        """
        pass

    def test_document_update(self):
        """Test case for document_update

        Update  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
