# coding: utf-8

"""
    Xprizo API

    Xprizo api endpoints  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@xprizo.com
    Generated by: https://openapi-generator.tech
"""

import unittest

import xprizo_sdk_py
from xprizo_sdk_py.model.report_model import ReportModel
from xprizo_sdk_py import configuration


class TestReportModel(unittest.TestCase):
    """ReportModel unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
