VERSION_YEAR = 2023
VERSION_MONTH = int('03')
VERSION_DAY = int('31')
VERSION_HOUR = int('09')
VERSION_MINUTE = int('38')
MAJOR_VERSION = 0
MINOR_VERSION = 27
PATCH_VERSION = 202303310938
version_date = '2023/03/31 09:38'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
