#ifndef NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION "6.2.2302-21-g9180f9b9"
#define NETGEN_VERSION_MAJOR 6
#define NETGEN_VERSION_MINOR 2
#define NETGEN_VERSION_PATCH 2302
#define NETGEN_VERSION_TWEAK 21
#define NETGEN_VERSION_HASH "g9180f9b9"
#endif // NETGEN_VERSION_HPP_INCLUDED
