# coding: utf-8

"""
    Open Bank Project API

    An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2023. Licensed under the AGPL and commercial licences.  # noqa: E501

    OpenAPI spec version: v5.0.0
    Contact: contact@tesobe.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import obp_python
from obp_python.api.dynamic_message_doc_api import DynamicMessageDocApi  # noqa: E501
from obp_python.rest import ApiException


class TestDynamicMessageDocApi(unittest.TestCase):
    """DynamicMessageDocApi unit test stubs"""

    def setUp(self):
        self.api = obp_python.api.dynamic_message_doc_api.DynamicMessageDocApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_o_bpv4_0_0_create_bank_level_dynamic_message_doc(self):
        """Test case for o_bpv4_0_0_create_bank_level_dynamic_message_doc

        Create Bank Level Dynamic Message Doc  # noqa: E501
        """
        pass

    def test_o_bpv4_0_0_create_dynamic_message_doc(self):
        """Test case for o_bpv4_0_0_create_dynamic_message_doc

        Create Dynamic Message Doc  # noqa: E501
        """
        pass

    def test_o_bpv4_0_0_delete_bank_level_dynamic_message_doc(self):
        """Test case for o_bpv4_0_0_delete_bank_level_dynamic_message_doc

        Delete Bank Level Dynamic Message Doc  # noqa: E501
        """
        pass

    def test_o_bpv4_0_0_delete_dynamic_message_doc(self):
        """Test case for o_bpv4_0_0_delete_dynamic_message_doc

        Delete Dynamic Message Doc  # noqa: E501
        """
        pass

    def test_o_bpv4_0_0_get_all_bank_level_dynamic_message_docs(self):
        """Test case for o_bpv4_0_0_get_all_bank_level_dynamic_message_docs

        Get all Bank Level Dynamic Message Docs  # noqa: E501
        """
        pass

    def test_o_bpv4_0_0_get_all_dynamic_message_docs(self):
        """Test case for o_bpv4_0_0_get_all_dynamic_message_docs

        Get all Dynamic Message Docs  # noqa: E501
        """
        pass

    def test_o_bpv4_0_0_get_bank_level_dynamic_message_doc(self):
        """Test case for o_bpv4_0_0_get_bank_level_dynamic_message_doc

        Get Bank Level Dynamic Message Doc  # noqa: E501
        """
        pass

    def test_o_bpv4_0_0_get_dynamic_message_doc(self):
        """Test case for o_bpv4_0_0_get_dynamic_message_doc

        Get Dynamic Message Doc  # noqa: E501
        """
        pass

    def test_o_bpv4_0_0_update_bank_level_dynamic_message_doc(self):
        """Test case for o_bpv4_0_0_update_bank_level_dynamic_message_doc

        Update Bank Level Dynamic Message Doc  # noqa: E501
        """
        pass

    def test_o_bpv4_0_0_update_dynamic_message_doc(self):
        """Test case for o_bpv4_0_0_update_dynamic_message_doc

        Update Dynamic Message Doc  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
