# coding: utf-8

"""
    Open Bank Project API

    An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2023. Licensed under the AGPL and commercial licences.  # noqa: E501

    OpenAPI spec version: v5.0.0
    Contact: contact@tesobe.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import obp_python
from obp_python.api.endpoint_mapping_api import EndpointMappingApi  # noqa: E501
from obp_python.rest import ApiException


class TestEndpointMappingApi(unittest.TestCase):
    """EndpointMappingApi unit test stubs"""

    def setUp(self):
        self.api = obp_python.api.endpoint_mapping_api.EndpointMappingApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_o_bpv4_0_0_create_bank_level_endpoint_mapping(self):
        """Test case for o_bpv4_0_0_create_bank_level_endpoint_mapping

        Create Bank Level Endpoint Mapping  # noqa: E501
        """
        pass

    def test_o_bpv4_0_0_create_endpoint_mapping(self):
        """Test case for o_bpv4_0_0_create_endpoint_mapping

        Create Endpoint Mapping  # noqa: E501
        """
        pass

    def test_o_bpv4_0_0_delete_bank_level_endpoint_mapping(self):
        """Test case for o_bpv4_0_0_delete_bank_level_endpoint_mapping

        Delete Bank Level Endpoint Mapping  # noqa: E501
        """
        pass

    def test_o_bpv4_0_0_delete_endpoint_mapping(self):
        """Test case for o_bpv4_0_0_delete_endpoint_mapping

        Delete Endpoint Mapping  # noqa: E501
        """
        pass

    def test_o_bpv4_0_0_get_all_bank_level_endpoint_mappings(self):
        """Test case for o_bpv4_0_0_get_all_bank_level_endpoint_mappings

        Get all Bank Level Endpoint Mappings  # noqa: E501
        """
        pass

    def test_o_bpv4_0_0_get_all_endpoint_mappings(self):
        """Test case for o_bpv4_0_0_get_all_endpoint_mappings

        Get all Endpoint Mappings  # noqa: E501
        """
        pass

    def test_o_bpv4_0_0_get_bank_level_endpoint_mapping(self):
        """Test case for o_bpv4_0_0_get_bank_level_endpoint_mapping

        Get Bank Level Endpoint Mapping  # noqa: E501
        """
        pass

    def test_o_bpv4_0_0_get_endpoint_mapping(self):
        """Test case for o_bpv4_0_0_get_endpoint_mapping

        Get Endpoint Mapping by Id  # noqa: E501
        """
        pass

    def test_o_bpv4_0_0_update_bank_level_endpoint_mapping(self):
        """Test case for o_bpv4_0_0_update_bank_level_endpoint_mapping

        Update Bank Level Endpoint Mapping  # noqa: E501
        """
        pass

    def test_o_bpv4_0_0_update_endpoint_mapping(self):
        """Test case for o_bpv4_0_0_update_endpoint_mapping

        Update Endpoint Mapping  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
