# -*- coding: utf-8 -*-
from setuptools import setup

package_dir = \
{'': 'src'}

packages = \
['ailab',
 'ailab.hub.chatgpt.chat_gpt_api_official.wrapper',
 'ailab.hub.chatgpt.chat_gpt_api_official.wrapper.test_data',
 'ailab.hub.huggingface.diffusers.alt_diffusion.wrapper',
 'ailab.hub.huggingface.diffusers.audio_diffusion.wrapper',
 'ailab.hub.huggingface.diffusers.cycle_diffusion.wrapper',
 'ailab.hub.huggingface.diffusers.dance_diffusion.wrapper',
 'ailab.hub.huggingface.diffusers.latency_diffusion.wrapper',
 'ailab.hub.huggingface.diffusers.stable_diffusion.attend_and_excite.wrapper',
 'ailab.hub.huggingface.diffusers.stable_diffusion.depth_to_image.wrapper',
 'ailab.hub.huggingface.diffusers.stable_diffusion.image_to_image.wrapper',
 'ailab.hub.huggingface.diffusers.stable_diffusion.inpainting.wrapper',
 'ailab.hub.huggingface.diffusers.stable_diffusion.instruct_pix2pix.wrapper',
 'ailab.hub.huggingface.diffusers.stable_diffusion.multi_diffusion.wrapper',
 'ailab.hub.huggingface.diffusers.stable_diffusion.self_attention_guidance.wrapper',
 'ailab.hub.huggingface.diffusers.stable_diffusion.super-resolution.wrapper',
 'ailab.hub.huggingface.diffusers.stable_diffusion.text_to_image.wrapper',
 'ailab.hub.huggingface.transformers.audio.audio_classification.wrapper',
 'ailab.hub.huggingface.transformers.audio.automatic-speech-recognition.wrapper',
 'ailab.hub.huggingface.transformers.cv.depth_estimation.wrapper',
 'ailab.hub.huggingface.transformers.cv.image_classification.wrapper',
 'ailab.hub.huggingface.transformers.cv.image_segmentation.wrapper',
 'ailab.hub.huggingface.transformers.cv.object_detection.wrapper',
 'ailab.hub.huggingface.transformers.cv.video_classification.wrapper',
 'ailab.hub.huggingface.transformers.cv.zero_shot_image_classification.wrapper',
 'ailab.hub.huggingface.transformers.cv.zero_shot_object_detection.wrapper',
 'ailab.hub.huggingface.transformers.multimodal.document_question_answering.wrapper',
 'ailab.hub.huggingface.transformers.multimodal.feature_extraction.wrapper',
 'ailab.hub.huggingface.transformers.multimodal.image_to_text.wrapper',
 'ailab.hub.huggingface.transformers.multimodal.visual_question_answering.wrapper',
 'ailab.hub.huggingface.transformers.nlp.conversational.wrapper',
 'ailab.hub.huggingface.transformers.nlp.fill_mask.wrapper',
 'ailab.hub.huggingface.transformers.nlp.question_answering.wrapper',
 'ailab.hub.huggingface.transformers.nlp.sentiment-analysis.wrapper',
 'ailab.hub.huggingface.transformers.nlp.summarization.wrapper',
 'ailab.hub.huggingface.transformers.nlp.table_question_answering.wrapper',
 'ailab.hub.huggingface.transformers.nlp.text2text_generation.wrapper',
 'ailab.hub.huggingface.transformers.nlp.text_classification.wrapper',
 'ailab.hub.huggingface.transformers.nlp.text_generation.wrapper',
 'ailab.hub.huggingface.transformers.nlp.token_classification.wrapper',
 'ailab.hub.huggingface.transformers.nlp.translation.wrapper',
 'ailab.hub.huggingface.transformers.nlp.zero_shot_classification.wrapper',
 'ailab.hub.yolo.wrapper.yolov5',
 'ailab.hub.yolo.wrapper.yolov5.classify',
 'ailab.hub.yolo.wrapper.yolov5.models',
 'ailab.hub.yolo.wrapper.yolov5.segment',
 'ailab.hub.yolo.wrapper.yolov5.utils',
 'ailab.hub.yolo.wrapper.yolov5.utils.aws',
 'ailab.hub.yolo.wrapper.yolov5.utils.flask_rest_api',
 'ailab.hub.yolo.wrapper.yolov5.utils.loggers',
 'ailab.hub.yolo.wrapper.yolov5.utils.loggers.clearml',
 'ailab.hub.yolo.wrapper.yolov5.utils.loggers.comet',
 'ailab.hub.yolo.wrapper.yolov5.utils.loggers.wandb',
 'ailab.hub.yolo.wrapper.yolov5.utils.segment']

package_data = \
{'': ['*'],
 'ailab': ['hub/chatgpt/chat_gpt_api_official/*',
           'hub/huggingface/diffusers/*',
           'hub/huggingface/diffusers/alt_diffusion/*',
           'hub/huggingface/diffusers/audio_diffusion/*',
           'hub/huggingface/diffusers/cycle_diffusion/*',
           'hub/huggingface/diffusers/dance_diffusion/*',
           'hub/huggingface/diffusers/latency_diffusion/*',
           'hub/huggingface/diffusers/stable_diffusion/*',
           'hub/huggingface/diffusers/stable_diffusion/attend_and_excite/*',
           'hub/huggingface/diffusers/stable_diffusion/depth_to_image/*',
           'hub/huggingface/diffusers/stable_diffusion/image_to_image/*',
           'hub/huggingface/diffusers/stable_diffusion/inpainting/*',
           'hub/huggingface/diffusers/stable_diffusion/instruct_pix2pix/*',
           'hub/huggingface/diffusers/stable_diffusion/multi_diffusion/*',
           'hub/huggingface/diffusers/stable_diffusion/self_attention_guidance/*',
           'hub/huggingface/diffusers/stable_diffusion/super-resolution/*',
           'hub/huggingface/diffusers/stable_diffusion/text_to_image/*',
           'hub/huggingface/transformers/*',
           'hub/huggingface/transformers/audio/audio_classification/*',
           'hub/huggingface/transformers/audio/automatic-speech-recognition/*',
           'hub/huggingface/transformers/cv/depth_estimation/*',
           'hub/huggingface/transformers/cv/image_classification/*',
           'hub/huggingface/transformers/cv/image_segmentation/*',
           'hub/huggingface/transformers/cv/object_detection/*',
           'hub/huggingface/transformers/cv/video_classification/*',
           'hub/huggingface/transformers/cv/zero_shot_image_classification/*',
           'hub/huggingface/transformers/cv/zero_shot_object_detection/*',
           'hub/huggingface/transformers/multimodal/document_question_answering/*',
           'hub/huggingface/transformers/multimodal/feature_extraction/*',
           'hub/huggingface/transformers/multimodal/image_to_text/*',
           'hub/huggingface/transformers/multimodal/visual_question_answering/*',
           'hub/huggingface/transformers/nlp/conversational/*',
           'hub/huggingface/transformers/nlp/fill_mask/*',
           'hub/huggingface/transformers/nlp/question_answering/*',
           'hub/huggingface/transformers/nlp/sentiment-analysis/*',
           'hub/huggingface/transformers/nlp/summarization/*',
           'hub/huggingface/transformers/nlp/table_question_answering/*',
           'hub/huggingface/transformers/nlp/text2text_generation/*',
           'hub/huggingface/transformers/nlp/text_classification/*',
           'hub/huggingface/transformers/nlp/text_generation/*',
           'hub/huggingface/transformers/nlp/token_classification/*',
           'hub/huggingface/transformers/nlp/translation/*',
           'hub/huggingface/transformers/nlp/zero_shot_classification/*',
           'hub/yolo/wrapper/*'],
 'ailab.hub.yolo.wrapper.yolov5': ['.git/*',
                                   '.git/hooks/*',
                                   '.git/info/*',
                                   '.git/logs/*',
                                   '.git/logs/refs/heads/*',
                                   '.git/logs/refs/remotes/origin/*',
                                   '.git/objects/06/*',
                                   '.git/objects/16/*',
                                   '.git/objects/18/*',
                                   '.git/objects/1b/*',
                                   '.git/objects/1c/*',
                                   '.git/objects/20/*',
                                   '.git/objects/2a/*',
                                   '.git/objects/33/*',
                                   '.git/objects/3e/*',
                                   '.git/objects/45/*',
                                   '.git/objects/4d/*',
                                   '.git/objects/55/*',
                                   '.git/objects/78/*',
                                   '.git/objects/84/*',
                                   '.git/objects/85/*',
                                   '.git/objects/86/*',
                                   '.git/objects/8e/*',
                                   '.git/objects/a3/*',
                                   '.git/objects/a6/*',
                                   '.git/objects/ad/*',
                                   '.git/objects/ae/*',
                                   '.git/objects/ba/*',
                                   '.git/objects/c1/*',
                                   '.git/objects/c5/*',
                                   '.git/objects/c6/*',
                                   '.git/objects/c9/*',
                                   '.git/objects/ca/*',
                                   '.git/objects/d2/*',
                                   '.git/objects/d6/*',
                                   '.git/objects/ea/*',
                                   '.git/objects/ef/*',
                                   '.git/objects/f1/*',
                                   '.git/objects/f6/*',
                                   '.git/objects/fe/*',
                                   '.git/objects/ff/*',
                                   '.git/objects/pack/*',
                                   '.git/refs/heads/*',
                                   '.git/refs/remotes/origin/*',
                                   '.github/*',
                                   '.github/ISSUE_TEMPLATE/*',
                                   '.github/workflows/*',
                                   'data/*',
                                   'data/hyps/*',
                                   'data/images/*',
                                   'data/scripts/*',
                                   'test_data/*'],
 'ailab.hub.yolo.wrapper.yolov5.models': ['hub/*', 'segment/*'],
 'ailab.hub.yolo.wrapper.yolov5.utils': ['docker/*', 'google_app_engine/*']}

install_requires = \
['pyailab>0.0']

setup_kwargs = {
    'name': 'ifly-ailab',
    'version': '0.1.1',
    'description': 'a iflytek ailab library ...',
    'long_description': None,
    'author': 'ybyang',
    'author_email': 'ybyang7@iflytek.com',
    'maintainer': None,
    'maintainer_email': None,
    'url': None,
    'package_dir': package_dir,
    'packages': packages,
    'package_data': package_data,
    'install_requires': install_requires,
    'python_requires': '>3.7',
}


setup(**setup_kwargs)
