"""
    Delphix DCT API

    Delphix DCT API  # noqa: E501

    The version of the OpenAPI document: 3.1.0
    Contact: support@delphix.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import delphix.api.gateway
from delphix.api.gateway.model.environment_repository import EnvironmentRepository
globals()['EnvironmentRepository'] = EnvironmentRepository
from delphix.api.gateway.model.snapshot_compatible_repositories import SnapshotCompatibleRepositories


class TestSnapshotCompatibleRepositories(unittest.TestCase):
    """SnapshotCompatibleRepositories unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSnapshotCompatibleRepositories(self):
        """Test SnapshotCompatibleRepositories"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SnapshotCompatibleRepositories()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
