# Generated by Django 2.2.28 on 2022-05-10 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alipay', '0009_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='alipaypayment',
            name='refund_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
