
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-03-30T09:41:13+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "b183f861c56c65f6171f154322526dc6d3a2471b",
 "version": "2022.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
