# (generated with --quick)

import glob
import numpy as np
import os
import re
import torch
from torch import nn
from typing import Any

def network_init(m) -> None: ...
def schedule(schdl, step) -> Any: ...
def soft_update_params(net, target_net, tau) -> None: ...
def to_torch(xs, device) -> tuple: ...
def update_linear_schedule(optimizer, epoch, total_num_epochs, initial_lr) -> None: ...
