# AUTOGENERATED! DO NOT EDIT! File to edit: ../../notebooks/CLI_DataSource.ipynb.

# %% auto 0
__all__ = ['app']

# %% ../../notebooks/CLI_DataSource.ipynb 3
import airt

from ..client import _fix_cli_doc_string

# %% ../../notebooks/CLI_DataSource.ipynb 4
from airt._cli.ds import app as _app

app = _app

_fix_cli_doc_string(app, "ds")
