
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-03-29T09:32:06+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "47740fb4171b034fb938de834a02a5abe360a396",
 "version": "2023.3.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
