
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-03-30T12:21:00+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "3f2a1da3b1ff51a1473dfb4e0e512b3d3b793201",
 "version": "5.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
