#ifndef NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION "6.2.2302-10-g5541bcfb"
#define NETGEN_VERSION_MAJOR 6
#define NETGEN_VERSION_MINOR 2
#define NETGEN_VERSION_PATCH 2302
#define NETGEN_VERSION_TWEAK 10
#define NETGEN_VERSION_HASH "g5541bcfb"
#endif // NETGEN_VERSION_HPP_INCLUDED
