
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-03-31T18:55:43+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "17ea335ca7d9abe49cbe6d9d4923ff908ab1437e",
 "version": "0.0.14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
