
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-03-31T10:19:39+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "8470454e294f1838635ccf733c6e8ec74aa77568",
 "version": "1.2.0rc3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
