# AUTOGENERATED! DO NOT EDIT! File to edit: ../../notebooks/CLI_ApiKey.ipynb.

# %% auto 0
__all__ = ['app']

# %% ../../notebooks/CLI_ApiKey.ipynb 3
import airt

from ..client import _fix_cli_doc_string

# %% ../../notebooks/CLI_ApiKey.ipynb 4
from airt._cli.api_key import app as _app

app = _app

_fix_cli_doc_string(app, "api_key")
