# -*- coding: utf-8 -*-
from setuptools import setup

packages = \
['nonebot_plugin_docs', 'nonebot_plugin_docs.drivers']

package_data = \
{'': ['*'],
 'nonebot_plugin_docs': ['dist/*',
                         'dist/assets/css/*',
                         'dist/assets/js/*',
                         'dist/changelog/*',
                         'dist/docs/*',
                         'dist/docs/advanced/adapter/*',
                         'dist/docs/advanced/dependency/*',
                         'dist/docs/advanced/driver/*',
                         'dist/docs/advanced/matcher-provider/*',
                         'dist/docs/advanced/matcher/*',
                         'dist/docs/advanced/plugin-info/*',
                         'dist/docs/advanced/plugin-nesting/*',
                         'dist/docs/advanced/requiring/*',
                         'dist/docs/advanced/routing/*',
                         'dist/docs/advanced/runtime-hook/*',
                         'dist/docs/advanced/session-updating/*',
                         'dist/docs/api/adapters/index/*',
                         'dist/docs/api/config/*',
                         'dist/docs/api/consts/*',
                         'dist/docs/api/dependencies/index/*',
                         'dist/docs/api/dependencies/utils/*',
                         'dist/docs/api/drivers/aiohttp/*',
                         'dist/docs/api/drivers/fastapi/*',
                         'dist/docs/api/drivers/httpx/*',
                         'dist/docs/api/drivers/index/*',
                         'dist/docs/api/drivers/none/*',
                         'dist/docs/api/drivers/quart/*',
                         'dist/docs/api/drivers/websockets/*',
                         'dist/docs/api/exception/*',
                         'dist/docs/api/index/*',
                         'dist/docs/api/log/*',
                         'dist/docs/api/matcher/*',
                         'dist/docs/api/message/*',
                         'dist/docs/api/params/*',
                         'dist/docs/api/permission/*',
                         'dist/docs/api/plugin/index/*',
                         'dist/docs/api/plugin/load/*',
                         'dist/docs/api/plugin/manager/*',
                         'dist/docs/api/plugin/on/*',
                         'dist/docs/api/plugin/plugin/*',
                         'dist/docs/api/rule/*',
                         'dist/docs/api/typing/*',
                         'dist/docs/api/utils/*',
                         'dist/docs/appendices/api-calling/*',
                         'dist/docs/appendices/config/*',
                         'dist/docs/appendices/log/*',
                         'dist/docs/appendices/overload/*',
                         'dist/docs/appendices/permission/*',
                         'dist/docs/appendices/rule/*',
                         'dist/docs/appendices/session-control/*',
                         'dist/docs/appendices/session-state/*',
                         'dist/docs/appendices/whats-next/*',
                         'dist/docs/best-practice/data-storing/*',
                         'dist/docs/best-practice/deployment/*',
                         'dist/docs/best-practice/error-tracking/*',
                         'dist/docs/best-practice/scheduler/*',
                         'dist/docs/best-practice/testing/*',
                         'dist/docs/best-practice/testing/behavior/*',
                         'dist/docs/best-practice/testing/mock-network/*',
                         'dist/docs/community/contact/*',
                         'dist/docs/community/contributing/*',
                         'dist/docs/developer/adapter-writing/*',
                         'dist/docs/developer/plugin-publishing/*',
                         'dist/docs/editor-support/*',
                         'dist/docs/next/*',
                         'dist/docs/next/advanced/adapter/*',
                         'dist/docs/next/advanced/dependency/*',
                         'dist/docs/next/advanced/driver/*',
                         'dist/docs/next/advanced/matcher-provider/*',
                         'dist/docs/next/advanced/matcher/*',
                         'dist/docs/next/advanced/plugin-info/*',
                         'dist/docs/next/advanced/plugin-nesting/*',
                         'dist/docs/next/advanced/requiring/*',
                         'dist/docs/next/advanced/routing/*',
                         'dist/docs/next/advanced/runtime-hook/*',
                         'dist/docs/next/advanced/session-updating/*',
                         'dist/docs/next/api/adapters/index/*',
                         'dist/docs/next/api/config/*',
                         'dist/docs/next/api/consts/*',
                         'dist/docs/next/api/dependencies/index/*',
                         'dist/docs/next/api/dependencies/utils/*',
                         'dist/docs/next/api/drivers/aiohttp/*',
                         'dist/docs/next/api/drivers/fastapi/*',
                         'dist/docs/next/api/drivers/httpx/*',
                         'dist/docs/next/api/drivers/index/*',
                         'dist/docs/next/api/drivers/none/*',
                         'dist/docs/next/api/drivers/quart/*',
                         'dist/docs/next/api/drivers/websockets/*',
                         'dist/docs/next/api/exception/*',
                         'dist/docs/next/api/index/*',
                         'dist/docs/next/api/log/*',
                         'dist/docs/next/api/matcher/*',
                         'dist/docs/next/api/message/*',
                         'dist/docs/next/api/params/*',
                         'dist/docs/next/api/permission/*',
                         'dist/docs/next/api/plugin/index/*',
                         'dist/docs/next/api/plugin/load/*',
                         'dist/docs/next/api/plugin/manager/*',
                         'dist/docs/next/api/plugin/on/*',
                         'dist/docs/next/api/plugin/plugin/*',
                         'dist/docs/next/api/rule/*',
                         'dist/docs/next/api/typing/*',
                         'dist/docs/next/api/utils/*',
                         'dist/docs/next/appendices/api-calling/*',
                         'dist/docs/next/appendices/config/*',
                         'dist/docs/next/appendices/log/*',
                         'dist/docs/next/appendices/overload/*',
                         'dist/docs/next/appendices/permission/*',
                         'dist/docs/next/appendices/rule/*',
                         'dist/docs/next/appendices/session-control/*',
                         'dist/docs/next/appendices/session-state/*',
                         'dist/docs/next/appendices/whats-next/*',
                         'dist/docs/next/best-practice/data-storing/*',
                         'dist/docs/next/best-practice/deployment/*',
                         'dist/docs/next/best-practice/error-tracking/*',
                         'dist/docs/next/best-practice/scheduler/*',
                         'dist/docs/next/best-practice/testing/*',
                         'dist/docs/next/best-practice/testing/behavior/*',
                         'dist/docs/next/best-practice/testing/mock-network/*',
                         'dist/docs/next/community/contact/*',
                         'dist/docs/next/community/contributing/*',
                         'dist/docs/next/developer/adapter-writing/*',
                         'dist/docs/next/developer/plugin-publishing/*',
                         'dist/docs/next/editor-support/*',
                         'dist/docs/next/quick-start/*',
                         'dist/docs/next/tutorial/application/*',
                         'dist/docs/next/tutorial/create-plugin/*',
                         'dist/docs/next/tutorial/event-data/*',
                         'dist/docs/next/tutorial/fundamentals/*',
                         'dist/docs/next/tutorial/handler/*',
                         'dist/docs/next/tutorial/matcher/*',
                         'dist/docs/next/tutorial/message/*',
                         'dist/docs/next/tutorial/store/*',
                         'dist/docs/quick-start/*',
                         'dist/docs/tutorial/application/*',
                         'dist/docs/tutorial/create-plugin/*',
                         'dist/docs/tutorial/event-data/*',
                         'dist/docs/tutorial/fundamentals/*',
                         'dist/docs/tutorial/handler/*',
                         'dist/docs/tutorial/matcher/*',
                         'dist/docs/tutorial/message/*',
                         'dist/docs/tutorial/store/*',
                         'dist/icons/*',
                         'dist/img/*',
                         'dist/search/*',
                         'dist/store/*']}

install_requires = \
['nonebot2>=2.0.0-beta.1,<3.0.0']

setup_kwargs = {
    'name': 'nonebot-plugin-docs',
    'version': '2.0.0rc4',
    'description': 'View NoneBot2 Docs Locally',
    'long_description': '<p align="center">\n  <a href="https://v2.nonebot.dev/"><img src="https://raw.githubusercontent.com/nonebot/nonebot2/master/docs/.vuepress/public/logo.png" width="200" height="200" alt="nonebot"></a>\n</p>\n\n<div align="center">\n\n# nonebot-plugin-docs\n\n_✨ NoneBot 本地文档插件 ✨_\n\n</div>\n\n<p align="center">\n  <a href="https://raw.githubusercontent.com/nonebot/nonebot2/master/LICENSE">\n    <img src="https://img.shields.io/github/license/nonebot/nonebot2.svg" alt="license">\n  </a>\n  <a href="https://pypi.python.org/pypi/nonebot-plugin-docs">\n    <img src="https://img.shields.io/pypi/v/nonebot-plugin-docs.svg" alt="pypi">\n  </a>\n  <img src="https://img.shields.io/badge/python-3.8+-blue.svg" alt="python">\n</p>\n\n## 使用方式\n\n加载插件并启动 Bot ，在浏览器内打开 `http://host:port/docs/`。\n\n具体网址会在控制台内输出。\n',
    'author': 'yanyongyu',
    'author_email': 'yyy@nonebot.dev',
    'maintainer': 'None',
    'maintainer_email': 'None',
    'url': 'https://github.com/nonebot/nonebot2/blob/master/packages/nonebot-plugin-docs',
    'packages': packages,
    'package_data': package_data,
    'install_requires': install_requires,
    'python_requires': '>=3.8,<4.0',
}


setup(**setup_kwargs)
