"""
    Merge Accounting API

    The unified API for building rich integrations with multiple Accounting & Finance platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest
from unittest.mock import MagicMock

import MergePythonSDK.accounting
from MergePythonSDK.accounting.model.tracking_category import TrackingCategory
globals()['TrackingCategory'] = TrackingCategory
from MergePythonSDK.accounting.model.paginated_tracking_category_list import PaginatedTrackingCategoryList
from MergePythonSDK.shared.api_client import ApiClient


class TestPaginatedTrackingCategoryList(unittest.TestCase):
    """PaginatedTrackingCategoryList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaginatedTrackingCategoryList(self):
        """Test PaginatedTrackingCategoryList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PaginatedTrackingCategoryList()  # noqa: E501

        """
        No test json responses were defined for PaginatedTrackingCategoryList
        """
        raw_json = None

        if raw_json is None:
            return

        response_mock = MagicMock()
        response_mock.data = raw_json

        deserialized = ApiClient().deserialize(response_mock, (PaginatedTrackingCategoryList,), False)

        assert deserialized is not None



if __name__ == '__main__':
    unittest.main()
