
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-03-30T21:20:51+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "c19ecb2f11f109838702d8a6b9bf795e3ad63ef2",
 "version": "1.0.4rc0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
