# coding: utf-8

"""
    Open Bank Project API

    An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2023. Licensed under the AGPL and commercial licences.  # noqa: E501

    OpenAPI spec version: v5.0.0
    Contact: contact@tesobe.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import obp_python
from obp_python.api.customer_message_api import CustomerMessageApi  # noqa: E501
from obp_python.rest import ApiException


class TestCustomerMessageApi(unittest.TestCase):
    """CustomerMessageApi unit test stubs"""

    def setUp(self):
        self.api = obp_python.api.customer_message_api.CustomerMessageApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_o_bpv1_4_0_create_customer_message(self):
        """Test case for o_bpv1_4_0_create_customer_message

        Create Customer Message  # noqa: E501
        """
        pass

    def test_o_bpv1_4_0_get_customers_messages(self):
        """Test case for o_bpv1_4_0_get_customers_messages

        Get Customer Messages for all Customers  # noqa: E501
        """
        pass

    def test_o_bpv4_0_0_create_customer_message(self):
        """Test case for o_bpv4_0_0_create_customer_message

        Create Customer Message  # noqa: E501
        """
        pass

    def test_o_bpv4_0_0_get_customer_messages(self):
        """Test case for o_bpv4_0_0_get_customer_messages

        Get Customer Messages for a Customer  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
