# coding: utf-8

"""
    Papermerge REST API

    Document management system designed for digital archives  # noqa: E501

    The version of the OpenAPI document: 2.1.0b12
    Generated by: https://openapi-generator.tech
"""

import unittest

import papermerge_restapi_client
from papermerge_restapi_client.model.nodes_download import NodesDownload
from papermerge_restapi_client import configuration


class TestNodesDownload(unittest.TestCase):
    """NodesDownload unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
