# -*- coding: utf-8 -*-
from setuptools import setup

packages = \
['mathmaker',
 'mathmaker.core',
 'mathmaker.lib',
 'mathmaker.lib.LaTeX',
 'mathmaker.lib.constants',
 'mathmaker.lib.core',
 'mathmaker.lib.document',
 'mathmaker.lib.document.content',
 'mathmaker.lib.document.content.algebra',
 'mathmaker.lib.document.content.calculation',
 'mathmaker.lib.document.content.geometry',
 'mathmaker.lib.document.frames',
 'mathmaker.lib.machine',
 'mathmaker.lib.old_style_sheet',
 'mathmaker.lib.old_style_sheet.exercise',
 'mathmaker.lib.old_style_sheet.exercise.question',
 'mathmaker.lib.tools',
 'mathmaker.lib.tools.generators',
 'mathmaker.settings']

package_data = \
{'': ['*'],
 'mathmaker': ['data/anglessets.db-dist',
               'data/anglessets.db-dist',
               'data/anglessets.db-dist',
               'data/anglessets.db-dist',
               'data/anglessets.db-dist',
               'data/anglessets.db-dist',
               'data/anglessets.db-dist',
               'data/anglessets.db-dist',
               'data/anglessets.db-dist',
               'data/anglessets.db-dist',
               'data/anglessets.db-dist',
               'data/anglessets.db-dist',
               'data/anglessets.db-dist',
               'data/anglessets_db_index.json',
               'data/anglessets_db_index.json',
               'data/anglessets_db_index.json',
               'data/anglessets_db_index.json',
               'data/anglessets_db_index.json',
               'data/anglessets_db_index.json',
               'data/anglessets_db_index.json',
               'data/anglessets_db_index.json',
               'data/anglessets_db_index.json',
               'data/anglessets_db_index.json',
               'data/anglessets_db_index.json',
               'data/anglessets_db_index.json',
               'data/anglessets_db_index.json',
               'data/db_index.json',
               'data/db_index.json',
               'data/db_index.json',
               'data/db_index.json',
               'data/db_index.json',
               'data/db_index.json',
               'data/db_index.json',
               'data/db_index.json',
               'data/db_index.json',
               'data/db_index.json',
               'data/db_index.json',
               'data/db_index.json',
               'data/db_index.json',
               'data/extra_translations.yaml',
               'data/extra_translations.yaml',
               'data/extra_translations.yaml',
               'data/extra_translations.yaml',
               'data/extra_translations.yaml',
               'data/extra_translations.yaml',
               'data/extra_translations.yaml',
               'data/extra_translations.yaml',
               'data/extra_translations.yaml',
               'data/extra_translations.yaml',
               'data/extra_translations.yaml',
               'data/extra_translations.yaml',
               'data/extra_translations.yaml',
               'data/fonts_list.txt',
               'data/fonts_list.txt',
               'data/fonts_list.txt',
               'data/fonts_list.txt',
               'data/fonts_list.txt',
               'data/fonts_list.txt',
               'data/fonts_list.txt',
               'data/fonts_list.txt',
               'data/fonts_list.txt',
               'data/fonts_list.txt',
               'data/fonts_list.txt',
               'data/fonts_list.txt',
               'data/fonts_list.txt',
               'data/frameworks/*',
               'data/frameworks/algebra/*',
               'data/frameworks/calculation/*',
               'data/frameworks/geometry/intercept_theorem/*',
               'data/frameworks/geometry/trigonometry/*',
               'data/frameworks/mental_calculation/*',
               'data/mathmaker.db-dist',
               'data/mathmaker.db-dist',
               'data/mathmaker.db-dist',
               'data/mathmaker.db-dist',
               'data/mathmaker.db-dist',
               'data/mathmaker.db-dist',
               'data/mathmaker.db-dist',
               'data/mathmaker.db-dist',
               'data/mathmaker.db-dist',
               'data/mathmaker.db-dist',
               'data/mathmaker.db-dist',
               'data/mathmaker.db-dist',
               'data/mathmaker.db-dist',
               'data/names/f/*',
               'data/names/m/*',
               'data/natural_nb_tuples.db-dist',
               'data/natural_nb_tuples.db-dist',
               'data/natural_nb_tuples.db-dist',
               'data/natural_nb_tuples.db-dist',
               'data/natural_nb_tuples.db-dist',
               'data/natural_nb_tuples.db-dist',
               'data/natural_nb_tuples.db-dist',
               'data/natural_nb_tuples.db-dist',
               'data/natural_nb_tuples.db-dist',
               'data/natural_nb_tuples.db-dist',
               'data/natural_nb_tuples.db-dist',
               'data/natural_nb_tuples.db-dist',
               'data/natural_nb_tuples.db-dist',
               'data/natural_nb_tuples_db_index.json',
               'data/natural_nb_tuples_db_index.json',
               'data/natural_nb_tuples_db_index.json',
               'data/natural_nb_tuples_db_index.json',
               'data/natural_nb_tuples_db_index.json',
               'data/natural_nb_tuples_db_index.json',
               'data/natural_nb_tuples_db_index.json',
               'data/natural_nb_tuples_db_index.json',
               'data/natural_nb_tuples_db_index.json',
               'data/natural_nb_tuples_db_index.json',
               'data/natural_nb_tuples_db_index.json',
               'data/natural_nb_tuples_db_index.json',
               'data/natural_nb_tuples_db_index.json',
               'data/shapes.db-dist',
               'data/shapes.db-dist',
               'data/shapes.db-dist',
               'data/shapes.db-dist',
               'data/shapes.db-dist',
               'data/shapes.db-dist',
               'data/shapes.db-dist',
               'data/shapes.db-dist',
               'data/shapes.db-dist',
               'data/shapes.db-dist',
               'data/shapes.db-dist',
               'data/shapes.db-dist',
               'data/shapes.db-dist',
               'data/shapes_db_index.json',
               'data/shapes_db_index.json',
               'data/shapes_db_index.json',
               'data/shapes_db_index.json',
               'data/shapes_db_index.json',
               'data/shapes_db_index.json',
               'data/shapes_db_index.json',
               'data/shapes_db_index.json',
               'data/shapes_db_index.json',
               'data/shapes_db_index.json',
               'data/shapes_db_index.json',
               'data/shapes_db_index.json',
               'data/shapes_db_index.json',
               'data/solids.db-dist',
               'data/solids.db-dist',
               'data/solids.db-dist',
               'data/solids.db-dist',
               'data/solids.db-dist',
               'data/solids.db-dist',
               'data/solids.db-dist',
               'data/solids.db-dist',
               'data/solids.db-dist',
               'data/solids.db-dist',
               'data/solids.db-dist',
               'data/solids.db-dist',
               'data/solids.db-dist',
               'data/solids_db_index.json',
               'data/solids_db_index.json',
               'data/solids_db_index.json',
               'data/solids_db_index.json',
               'data/solids_db_index.json',
               'data/solids_db_index.json',
               'data/solids_db_index.json',
               'data/solids_db_index.json',
               'data/solids_db_index.json',
               'data/solids_db_index.json',
               'data/solids_db_index.json',
               'data/solids_db_index.json',
               'data/solids_db_index.json',
               'data/vocabulary.yaml',
               'data/vocabulary.yaml',
               'data/vocabulary.yaml',
               'data/vocabulary.yaml',
               'data/vocabulary.yaml',
               'data/vocabulary.yaml',
               'data/vocabulary.yaml',
               'data/vocabulary.yaml',
               'data/vocabulary.yaml',
               'data/vocabulary.yaml',
               'data/vocabulary.yaml',
               'data/vocabulary.yaml',
               'data/vocabulary.yaml',
               'data/w3l/*',
               'data/w4l/*',
               'data/w5l/*',
               'data/wordings/*',
               'locale/*',
               'locale/en/LC_MESSAGES/*',
               'locale/en_GB/LC_MESSAGES/*',
               'locale/en_US/LC_MESSAGES/*',
               'locale/fr_FR/LC_MESSAGES/*'],
 'mathmaker.lib.LaTeX': ['templates/*'],
 'mathmaker.lib.document.frames': ['templates/*'],
 'mathmaker.settings': ['default/debug_conf.yaml',
                        'default/debug_conf.yaml',
                        'default/debug_conf.yaml',
                        'default/debug_conf.yaml',
                        'default/debug_conf.yaml',
                        'default/debug_conf.yaml',
                        'default/debug_conf.yaml',
                        'default/logging.yaml',
                        'default/logging.yaml',
                        'default/logging.yaml',
                        'default/logging.yaml',
                        'default/logging.yaml',
                        'default/logging.yaml',
                        'default/logging.yaml',
                        'default/logging_freebsd.yaml',
                        'default/logging_freebsd.yaml',
                        'default/logging_freebsd.yaml',
                        'default/logging_freebsd.yaml',
                        'default/logging_freebsd.yaml',
                        'default/logging_freebsd.yaml',
                        'default/logging_freebsd.yaml',
                        'default/mc_belts.json',
                        'default/mc_belts.json',
                        'default/mc_belts.json',
                        'default/mc_belts.json',
                        'default/mc_belts.json',
                        'default/mc_belts.json',
                        'default/mc_belts.json',
                        'default/mc_titles.json',
                        'default/mc_titles.json',
                        'default/mc_titles.json',
                        'default/mc_titles.json',
                        'default/mc_titles.json',
                        'default/mc_titles.json',
                        'default/mc_titles.json',
                        'default/user_config.yaml',
                        'default/user_config.yaml',
                        'default/user_config.yaml',
                        'default/user_config.yaml',
                        'default/user_config.yaml',
                        'default/user_config.yaml',
                        'default/user_config.yaml',
                        'default/user_config_windows.yaml',
                        'default/user_config_windows.yaml',
                        'default/user_config_windows.yaml',
                        'default/user_config_windows.yaml',
                        'default/user_config_windows.yaml',
                        'default/user_config_windows.yaml',
                        'default/user_config_windows.yaml']}

install_requires = \
['intspan>=1.6.1,<2.0.0',
 'mathmakerlib>=0.7.16,<0.8.0',
 'packaging>=21.3,<22.0',
 'polib>=1.1.1,<2.0.0',
 'python-daemon>=2.3.1,<3.0.0',
 'ruamel.yaml>=0.17.21,<0.18.0',
 'toml>=0.10.2,<0.11.0']

entry_points = \
{'console_scripts': ['mathmaker = mathmaker.cli:entry_point',
                     'mathmakerd = mathmaker.daemonized:entry_point']}

setup_kwargs = {
    'name': 'mathmaker',
    'version': '0.7.20',
    'description': 'Mathmaker creates automatically elementary maths exercises and their (detailed) answers.',
    'long_description': "|PyPI1| |PyPI2| |PyPI3| |Build Status| |Coveralls| |Documentation Status| |Maintenance| |PyPI4|\n\nOverview\n========\n\nMathmaker creates elementary maths worksheets with detailed solutions.\n\nThe output documents can be compiled into pdf files by lualatex.\nExamples of available themes are: first degree equations, pythagorean\ntheorem, fractions calculation...\n\nIt can run from command line, but can be controlled via http requests\ntoo.\n\n`Licence <https://gitlab.com/nicolas.hainaux/mathmaker/blob/master/LICENSE>`__\n`Documentation (master\nrelease) <http://mathmaker.readthedocs.io/en/master/index.html>`__\n`Documentation (latest development\nversion)) <http://mathmaker.readthedocs.io/en/dev/index.html>`__.\n\nQuickstart\n==========\n\nComplete install\n----------------\n\n.. note::\n\n  python3.6+ is mandatory for mathmaker to work, so check is installed on your system\n\n-  on Ubuntu 14.04 or later:\n\n   External dependencies:\n\n   ::\n\n       $ sudo apt-get install eukleides libxml2-utils gettext texlive-full\n\n   Note: to avoid installing ``texlive-full``, check the\n   `documentation <http://mathmaker.readthedocs.io/en/master/user_doc.html#install>`__.\n\n   Then:\n\n   ::\n\n       $ pip3 install mathmaker\n\n-  on FreeBSD 10.\\*:\n\n   External dependencies:\n\n   ::\n\n       $ sudo pkg install python36 py36-sqlite3 gettext eukleides libxml2 texlive-full\n       $ rehash\n\n       **note**\n\n       Because of a bug in current FreeBSD's eukleides package you'll\n       have to fix eukleides install. See\n       `here <http://mathmaker.readthedocs.io/en/master/user_doc.html#eukleides-fix>`__.\n\n   Once you're done, you can proceed installing mathmaker:\n\n   ::\n\n       $ pip3 install mathmaker\n\n       **note**\n\n       If you stumble upon an error during the install of the\n       python-daemon dependency, you'll find the way to solve it\n       `there <http://mathmaker.readthedocs.io/en/master/user_doc.html#python-daemon-error-at-install>`__\n\nBasic use\n---------\n\n::\n\n    $ mathmaker pythagorean-theorem-short-test > out.tex\n    $ lualatex out.tex\n\nor directly:\n\n::\n\n    $ mathmaker pythagorean-theorem-short-test --pdf > out.pdf\n\nGet the list of all provided sheets(3):\n\n::\n\n    $ mathmaker list\n\nTo get the command-line options, you can use ``mathmaker --help``.\n\nSeveral settings can be overriden by user defined values in\n``~/.config/mathmaker/user_config.yaml``. Read `the complete\ndocumentation <http://mathmaker.readthedocs.io/en/master/user_doc.html#user-settings>`__\nfor more information.\n\nAdvanced use\n------------\n\nIt's possible to create your own sheets in yaml. Read from `the complete\ndocumentation <http://mathmaker.readthedocs.io/en/master/user_doc.html#yaml-sheets>`__\nfor more information.\n\nContribute\n==========\n\nYou can contribute to mathmaker:\n\nAs a wordings contributor\n-------------------------\n\nMathmaker needs contexts for problems wordings. There are already some,\nbut the more there is, the better. Existing wordings can be found\n`here <https://gitlab.com/nicolas.hainaux/mathmaker/tree/dev/mathmaker/data/wordings>`__.\nYou can submit any new idea as an enhancement proposal\n`there <https://gitlab.com/nicolas.hainaux/mathmaker/issues>`__ (should\nbe written in english, french or german).\n\nAny question can be sent to nh dot techn (hosted at gmail dot com).\n\nAs a translator\n---------------\n\nYou can help translating mathmaker to your language (or any language you\nlike, if you have enough elementary maths vocabulary for that).\n\nIf the translation to your language isn't started yet, there are several\npot files to get\n`here <https://gitlab.com/nicolas.hainaux/mathmaker/tree/dev/mathmaker/locale>`__\n(see explanations about their respective roles\n`there <http://mathmaker.readthedocs.io/en/dev/dev_doc.html#the-real-and-the-fake-translation-files>`__).\nYou can use an editor like `poedit <https://poedit.net/>`__ or any other\nyou like better, to create po files from them and start to translate.\n\nIf you want to add missing translations, or to correct some, you can\nfind the po files in the subdirectories\n`here <https://gitlab.com/nicolas.hainaux/mathmaker/tree/dev/mathmaker/locale>`__.\n\nOnce you're done, you can make a pull request\n`here <https://gitlab.com/nicolas.hainaux/mathmaker/pulls>`__.\n\nAny question can be sent to nh dot techn (hosted at gmail dot com).\n\nAs a developer\n--------------\n\nBefore submitting a PR, please ensure you've had a look at the `writing\nrules <http://mathmaker.readthedocs.io/en/dev/dev_doc.html#writing-rules>`__.\n\nMore details can be found in the `documentation for\ndevelopers <http://mathmaker.readthedocs.io/en/dev/dev_index.html>`__.\n\nAny question can be sent to nh dot techn (hosted at gmail dot com).\n\nAdditional informations\n-----------------------\n\nContact: nh dot techn (hosted by gmail dot com)\n\n`Changelog <https://gitlab.com/nicolas.hainaux/mathmaker/blob/master/CHANGELOG.rst>`__\n\n`Contributors <https://gitlab.com/nicolas.hainaux/mathmaker/blob/master/CONTRIBUTORS.rst>`__\n\n.. |PyPI1| image:: https://img.shields.io/pypi/v/mathmaker.svg?maxAge=2592000\n   :target: https://pypi.python.org/pypi/mathmaker\n.. |PyPI2| image:: https://img.shields.io/pypi/status/mathmaker.svg?maxAge=2592000\n.. |PyPI3| image:: https://img.shields.io/pypi/pyversions/mathmaker.svg?maxAge=2592000\n.. |Build Status| image:: https://ci.appveyor.com/api/projects/status/88ay13trwvipaijb/branch/master?svg=true\n   :target: https://ci.appveyor.com/project/nicolashainaux/mathmakerlib-ho94f\n.. |Coveralls| image:: https://coveralls.io/repos/gitlab/nicolashainaux/mathmaker/badge.svg?branch=master\n   :target: https://coveralls.io/gitlab/nicolashainaux/mathmaker?branch=master\n.. |Documentation Status| image:: https://readthedocs.org/projects/mathmaker/badge/?version=latest\n   :target: https://mathmaker.readthedocs.io/en/latest/\n.. |Maintenance| image:: https://img.shields.io/maintenance/yes/2021.svg?maxAge=2592000\n.. |PyPI4| image:: https://img.shields.io/pypi/l/mathmaker.svg?maxAge=2592000\n   :target: https://gitlab.com/nicolas.hainaux/mathmaker/blob/master/LICENSE\n",
    'author': 'Nicolas Hainaux',
    'author_email': 'nh.techn@posteo.net',
    'maintainer': 'None',
    'maintainer_email': 'None',
    'url': 'None',
    'packages': packages,
    'package_data': package_data,
    'install_requires': install_requires,
    'entry_points': entry_points,
    'python_requires': '>=3.8,<4.0',
}


setup(**setup_kwargs)
