
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-03-29T10:49:36-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "8c1d877b8a406ffb0095659df3326449df49c0f0",
 "version": "0.1.0a90"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
