# coding: utf-8

"""
    Xprizo API

    Xprizo api endpoints  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@xprizo.com
    Generated by: https://openapi-generator.tech
"""

from xprizo_sdk_py.paths.api_item_add.post import ApiItemAddPost
from xprizo_sdk_py.paths.api_item_deletehash_id.delete import ApiItemDeletehashIdDelete
from xprizo_sdk_py.paths.api_item_list.get import ApiItemListGet
from xprizo_sdk_py.paths.api_item_merge_template.get import ApiItemMergeTemplateGet
from xprizo_sdk_py.paths.api_item_model.get import ApiItemModelGet
from xprizo_sdk_py.paths.api_item_pin_subscription.put import ApiItemPinSubscriptionPut
from xprizo_sdk_py.paths.api_item_set_amount.put import ApiItemSetAmountPut
from xprizo_sdk_py.paths.api_item_set_description.put import ApiItemSetDescriptionPut
from xprizo_sdk_py.paths.api_item_set_detail.put import ApiItemSetDetailPut
from xprizo_sdk_py.paths.api_item_set_image.put import ApiItemSetImagePut
from xprizo_sdk_py.paths.api_item_set_name.put import ApiItemSetNamePut
from xprizo_sdk_py.paths.api_item_set_property_image.put import ApiItemSetPropertyImagePut
from xprizo_sdk_py.paths.api_item_set_property.put import ApiItemSetPropertyPut
from xprizo_sdk_py.paths.api_item_subscribe_hash_id.put import ApiItemSubscribeHashIdPut
from xprizo_sdk_py.paths.api_item_subscriptions.put import ApiItemSubscriptionsPut
from xprizo_sdk_py.paths.api_item_transaction_report_transaction_id.get import ApiItemTransactionReportTransactionIdGet
from xprizo_sdk_py.paths.api_item_unpin_subscription.put import ApiItemUnpinSubscriptionPut
from xprizo_sdk_py.paths.api_item_unsubscribe_hash_id.delete import ApiItemUnsubscribeHashIdDelete


class ItemApi(
    ApiItemAddPost,
    ApiItemDeletehashIdDelete,
    ApiItemListGet,
    ApiItemMergeTemplateGet,
    ApiItemModelGet,
    ApiItemPinSubscriptionPut,
    ApiItemSetAmountPut,
    ApiItemSetDescriptionPut,
    ApiItemSetDetailPut,
    ApiItemSetImagePut,
    ApiItemSetNamePut,
    ApiItemSetPropertyImagePut,
    ApiItemSetPropertyPut,
    ApiItemSubscribeHashIdPut,
    ApiItemSubscriptionsPut,
    ApiItemTransactionReportTransactionIdGet,
    ApiItemUnpinSubscriptionPut,
    ApiItemUnsubscribeHashIdDelete,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
