
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-03-31T10:41:20-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "c2ac2a7a450558ec1cd5787114ff2270f6a9c26c",
 "version": "2023.3.31"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
