# Generated by Django 4.1.1 on 2023-01-19 05:21

from django.db import migrations, models
import erscipcard.models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PassType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='StateType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام کاربری')),
                ('personeli', models.CharField(max_length=20, unique=True, verbose_name='شماره پرسنلی')),
                ('etebar', models.CharField(max_length=10,validators=[erscipcard.models.valid_date], verbose_name='تاريخ اعتبار')),
                ('pic', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='تصویر')),
                ('number', models.IntegerField(default=1, unique=True, verbose_name='شماره کارت')),
            ],
        ),
    ]
