line_styles = {'solid': '-',
               'dashed': '--',
               'dash-dotted': '-.',
               'dotted': ':',
               'none': 'None'}

marker_styles = {'pixel': ',',
                 'point': '.',
                 'circle': 'o',
                 'plus': '+',
                 'plus filled': 'P',
                 'cross': 'x',
                 'cross filled': 'X',
                 'star': '*',
                 'triangle left': '<',
                 'triangle right': '>',
                 'triangle up': '^',
                 'triangle down': 'v',
                 'tri left': '3',
                 'tri right': '4',
                 'tri up': '2',
                 'tri down': '1',
                 'square': 's',
                 'pentagon': 'p',
                 'hexagon 1': 'h',
                 'hexagon 2': 'H',
                 'octagon': '8',
                 'diamond': 'D',
                 'thin diamond': 'd',
                 'vertical line': '|',
                 'horizontal line': '_',
                 'tick left' : 0,
                 'tick right' : 1,
                 'tick up' : 2,
                 'tick down' : 3,
                 'caret left' : 4,
                 'caret right' : 5,
                 'caret up' : 6,
                 'caret down' : 7,
                 'caret left base' : 8,
                 'caret right base' : 9,
                 'caret up base' : 10,
                 'caret down base' : 11,
                 'none': 'None'}