
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-03-31T22:05:26-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "2a199bf9b938f61277edc963e4777ff35b37e71b",
 "version": "2023.4.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
