
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-03-31T15:07:18-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "0eb603a9dced6ad4c40f114327e40500e4ddeb45",
 "version": "2023.3.31.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
